### ISSUE TITLE
2 things

### ISSUE THREAD

**Issue by working-name** [w3cub/docshub#10]
Hello there,

I have two things for you:

1. Dumbest implementation of anti-ad blocking ever, which is again absolutely against open source spirit - running ads that is. Selling my information to trash companies just so you can get $0.000004 for my visit.
https://user-images.githubusercontent.com/16505052/172843154-8f37bdfa-313e-460f-aafa-6f31309c68ad.mp4

2. Did you know devdocs.io exists?

**Comment by Counselor8** [comment]
No I didn't know

**Comment by icai** [comment]
Yes, I know. current project fork form devdocs. Code in here, you can do your personal version
